import type { Metadata } from "next";
import "./globals.css";
import Providers from "./lib/Providers";
import Footer from "@/components/ui/Footer/Footer";

export const metadata: Metadata = {
  title: "Doctors Portal",
  description: "generated by programming hero next level developers",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
